version: "3.10"

services:
  python-shell:
    dockerfile: ./Dockerfile
    #image: python:3.12-rc-bullseye
    network_mode: host
    expose:
      - "4200:8080"
    command: ["shellinabox", "-t", "-s", "/usr/bin/python3"]
